inventory/urls.py
from django.urls import path

from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('plane/list/', views.PlaneListView.as_view(), name='plane_list'),
    path('order/list/', views.OrderListView.as_view(), name='order_list'),
    # path('order/', views.OrderCreateView.as_view(), name='order'),
    path('order/<int:pk>/', views.StockOrderView.as_view(), name='order'),
    path(
        'order/<int:pk>/details/', views.OrderDetailView.as_view(),
        name='order_details'
    ),
    path(
        'order/<int:pk>/fill/', views.FillOrderView.as_view(),
        name='fill_order'
    ),
    path(
        'change/<int:pk>/status/', views.ChangePlaneStatusView.as_view(),
        name='change_plane_status'
    ),
    path(
        'order/<int:pk>/download/', views.OrderPDFView.as_view(),
        name='download_order_pdf'
    ),
    path(
        'order/list/download/', views.OrderListPDFView.as_view(),
        name='download_order_list_pdf'
    ),
]

inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('customauth.urls')),
    path('', include('inventory.urls')),
]

inventory/models.py
from django.db import models


class Planes(models.Model):
    STATUS_CHOICES = (
        ('air', 'Air'),
        ('land', 'Land'),
    )
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=25, choices=STATUS_CHOICES)

    class Meta:
        db_table = 'PLANES'

    def __str__(self):
        return self.name

    @property
    def get_actual_stock(self):
        total_stock = 0
        for stock in self.planestock.all():
            total_stock += stock.maximum_quantity
        return total_stock


class Base(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'BASE'

    def __str__(self):
        return self.name


class Attendants(models.Model):
    user_id = models.OneToOneField(
        "customauth.User", on_delete=models.SET_NULL, null=True,
        related_name="attendants",
    )
    plane_id = models.ForeignKey(
        "inventory.Planes", on_delete=models.SET_NULL, null=True,
        related_name="attendants",
    )

    class Meta:
        db_table = 'ATTENDANTS'

    def __str__(self):
        return f"{self.user_id.nif}"


class Providers(models.Model):
    user_id = models.OneToOneField(
        "customauth.User", on_delete=models.SET_NULL, null=True,
        related_name="providers"
    )
    base = models.ForeignKey(
        "inventory.Base", on_delete=models.SET_NULL, null=True,
        related_name="providers_base"
    )

    class Meta:
        db_table = "PROVIDERS"

    def __str__(self):
        return f"{self.user_id.nif}"


class Routes(models.Model):
    plane_id = models.ForeignKey(
        "inventory.Planes", on_delete=models.SET_NULL, null=True,
        related_name="routes"
    )
    origin = models.CharField(max_length=5)
    destination = models.CharField(max_length=5)

    class Meta:
        db_table = "ROUTES"

    def __str__(self):
        return f"{self.origin}-{self.destination}"


class Products(models.Model):
    name = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = "PRODUCTS"

    def __str__(self):
        return self.name


class PlaneStock(models.Model):
    plane_id = models.ForeignKey(
        "inventory.Planes", on_delete=models.SET_NULL, null=True,
        related_name="planestock"
    )
    product_id = models.ForeignKey(
        "inventory.Products", on_delete=models.SET_NULL, null=True,
        related_name="planestock"
    )
    quantity = models.PositiveIntegerField()
    maximum_quantity = models.PositiveIntegerField()

    class Meta:
        db_table = "planeSTOCK"

    def __str__(self):
        return f"{self.plane_id}"


class Orders(models.Model):
    attendant_id = models.ForeignKey(
        "inventory.Attendants", on_delete=models.SET_NULL, null=True,
        related_name="orders"
    )
    providers = models.ForeignKey(
        "inventory.Providers", on_delete=models.SET_NULL, null=True,
        related_name="orders"
    )
    base = models.ForeignKey(
        "inventory.Base", on_delete=models.SET_NULL, null=True,
        related_name="orders"
    )
    date = models.DateField()
    status = models.CharField(max_length=10)

    class Meta:
        db_table = "ORDERS"

    def __str__(self):
        return f"{self.id}"


class OrderLine(models.Model):
    product_id = models.ForeignKey(
        "inventory.Products", on_delete=models.SET_NULL, null=True,
        related_name="orderline"
    )
    order_id = models.ForeignKey(
        "inventory.Orders", on_delete=models.SET_NULL, null=True,
        related_name="orderline"
    )
    quantity = models.PositiveIntegerField()
    fill_quantity = models.PositiveIntegerField(default=0, blank=True)

    class Meta:
        db_table = "ORDERLINES"

    def __str__(self):
        return f"{self.product_id}"

    @property
    def total_product_price(self):
        if self.product_id and self.quantity:
            return self.product_id.price * self.quantity
        else:
            return 0


class Notifications(models.Model):
    user_id = models.ForeignKey(
        "customauth.User", on_delete=models.SET_NULL, null=True,
        related_name="notifications"
    )
    description = models.CharField(max_length=255)
    order_id = models.CharField(max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "NOTIFICATIONS"

    def __str__(self):
        return f"{self.user_id}"

inventory/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from crispy_forms.helper import FormHelper

from inventory.models import Orders, OrderLine


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = Orders
        fields = ['base', 'date']

        widgets = {
            'base': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Base'
            }),
            'date': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'
            })
        }


class OrderLineForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderLineForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = OrderLine
        fields = ['product_id', 'quantity']

        widgets = {
            'product_id': forms.Select(attrs={
                'class': 'form-control',
            }),
            'quantity': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Quantity'
            })
        }


OrderLineFormSet = inlineformset_factory(
    Orders, OrderLine, form=OrderLineForm, min_num=1,
    extra=0, can_delete=True
)

inventory/views/dashboard.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

from inventory.models import Planes, Orders, Attendants, Providers


class DashboardView(LoginRequiredMixin, View):
    """ Dashboard view """
    template_name = 'dashboard/dashboard.html'
    login_url = 'customauth:login'

    def get(self, request):
        context = {
            'plane': Planes.objects.all().count(),
            'planes': Planes.objects.all(),
            'order': Orders.objects.all().count(),
            'attendant': Attendants.objects.all().count(),
            'provider': Providers.objects.all().count(),
        }
        return render(request, self.template_name, context)

inventory/views/inventory.py
import logging
from django.views.generic import ListView, View, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy

from customauth.models import User
from inventory.models import (
    Attendants, Orders, Notifications, Planes, OrderLine, PlaneStock, Base
)
from inventory.forms import OrderForm, OrderLineFormSet

logger = logging.getLogger(__name__)


class PlaneListView(LoginRequiredMixin, View):
    template_name = 'inventory/plane_list.html'
    login_url = 'customauth:login'

    def get(self, request, *args, **kwargs):
        try:
            planes = Attendants.objects.get(user_id=request.user).plane_id
        except Attendants.DoesNotExist:
            planes = Attendants.objects.none()
        context = {
            'planes': planes
        }
        return render(request, self.template_name, context)


class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'inventory/order_list.html'
    login_url = 'customauth:login'
    model = Orders


class OrderView(LoginRequiredMixin, View):
    template_name = 'inventory/order.html'
    login_url = 'customauth:login'
    model = Orders

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template_name, context)


class StockOrderView(LoginRequiredMixin, View):
    template_name = 'inventory/stock_order.html'
    login_url = 'customauth:login'
    model = Orders

    def get(self, request, *args, **kwargs):
        plane = Planes.objects.get(pk=self.kwargs['pk'])
        bases = Base.objects.all()
        context = {
            'plane': plane,
            'bases': bases,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        plane = Planes.objects.get(pk=self.kwargs['pk'])
        base_id = request.POST.get('base')
        date = request.POST.get('date')
        base = Base.objects.get(pk=base_id)
        order = Orders.objects.create(
            attendant_id=request.user.attendants,
            base=base,
            date=date,
        )
        for stock in plane.planestock.all():
            quantity = request.POST.get(f'{stock.id}_quantity')
            print(quantity)
            if quantity:
                total_quantity = int(stock.quantity) + int(quantity)
                if stock.maximum_quantity >= total_quantity:
                    OrderLine.objects.create(
                        product_id=stock.product_id,
                        order_id=order,
                        quantity=quantity,
                    )
                else:
                    messages.error(
                        request,
                        f'{stock.product_id} is exceeded the max stock'
                    )
                    Orders.objects.get(pk=order.pk).delete()
                    return redirect(reverse_lazy(
                        'inventory:order', kwargs={'pk': plane.pk}
                    ))
        for provider in base.providers_base.all():
            Notifications.objects.create(
                user_id=provider.user_id,
                order_id=order.pk,
                description=f'New Order added by {self.request.user.name}'
            )
        return redirect('inventory:order_details', pk=order.pk)


class OrderCreateView(LoginRequiredMixin, CreateView):
    """ Order create view """
    template_name = "inventory/order.html"
    login_url = 'customauth:login'
    model = Orders
    form_class = OrderForm
    formset_class = OrderLineFormSet

    def get_context_data(self, **kwargs):
        assert self.formset_class is not None, "No formset class specified"
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['line_formset'] = self.formset_class(
                self.request.POST, instance=self.object
            )
        else:
            context['line_formset'] = self.formset_class(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        line_formset = context['line_formset']
        if not line_formset.is_valid():
            return super().form_invalid(form)
        self.object = form.save()
        attendant = Attendants.objects.get(user_id=self.request.user)
        self.object.attendant_id = attendant
        self.object.save()
        line_formset.instance = self.object
        # line_formset.order_id = self.object
        line_formset.save()
        providers = User.objects.filter(user_type='provider')
        for provider in providers:
            Notifications.objects.create(
                user_id=provider,
                order_id=self.object.pk,
                description=f'New Order added by {self.request.user.name}'
            )
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request, 'Order has been created successfully!'
        )
        logger.debug(f'Order was created for {self.object}')
        return reverse_lazy(
            "inventory:order_list"
        )

    def error_url(self):
        messages.success(
            self.request, 'Invalid Data, Please try again!'
        )
        logger.debug(f'Order was created for {self.object}')
        return reverse_lazy("inventory:order_list")


class OrderDetailView(LoginRequiredMixin, DetailView):
    """ Order details view """
    model = Orders
    template_name = 'inventory/order_details.html'
    login_url = 'customauth:login'


class FillOrderView(LoginRequiredMixin, View):
    """ Order details view """
    model = Orders
    template_name = 'inventory/fill_order.html'
    login_url = 'customauth:login'

    def get(self, request, *args, **kwargs):
        order = Orders.objects.get(pk=self.kwargs['pk'])
        context = {
            'object': order
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        order = Orders.objects.get(pk=self.kwargs['pk'])
        for product in order.orderline.all():
            quantity = request.POST.get(f'{product.id}_quantity')
            if quantity:
                total_quantity = int(product.fill_quantity) + int(quantity)
                if product.quantity >= total_quantity:
                    product.fill_quantity = int(product.fill_quantity) + int(quantity)  # noqa
                    product.save()
                    stock = PlaneStock.objects.get(
                        product_id=product.product_id,
                    )
                    stock.quantity += int(quantity)
                    stock.save()
                else:
                    messages.error(
                        self.request, 'Not enough quantity for this product!'
                    )
        order.providers = self.request.user.providers
        order.save()
        status = 'fill'
        for line in order.orderline.all():
            if line.quantity != line.fill_quantity:
                status = 'not filled'
                break
        if status == 'fill':
            Notifications.objects.create(
                user_id=order.attendant_id.user_id,
                description="Your order has been filled",
                order_id=order.pk,
            )
        context = {
            'object': order
        }
        return render(request, self.template_name, context)


class ChangePlaneStatusView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        plane = Planes.objects.get(pk=self.kwargs['pk'])
        if plane.status == 'air':
            plane.status = 'land'
        else:
            plane.status = 'air'
        plane.save()
        return redirect('inventory:plane_list')

inventory/views/pdf_download.py
# importing the necessary libraries
from io import BytesIO
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import get_template
from xhtml2pdf import pisa

from inventory.models import Orders


# defining the function to convert an HTML file to a PDF file
def html_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None


# Creating a class based view
class OrderPDFView(LoginRequiredMixin, View):
    login_url = 'customauth:login'

    def get(self, request, *args, **kwargs):
        order = Orders.objects.filter(pk=self.kwargs['pk'])
        context = {
            'orders': order,
        }
        # getting the template
        pdf = html_to_pdf('inventory/order_pdf.html', context)
        # rendering the template
        return HttpResponse(pdf, content_type='application/pdf')


class OrderListPDFView(LoginRequiredMixin, View):
    login_url = 'customauth:login'

    def get(self, request, *args, **kwargs):
        date = request.GET.get('download_date')
        order = Orders.objects.filter(date=date)
        context = {
            'orders': order,
        }
        # getting the template
        pdf = html_to_pdf('inventory/order_pdf.html', context)
        # rendering the template
        return HttpResponse(pdf, content_type='application/pdf')

templates/inventory/fill_order.html
{% extends "dashboard/base/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block stylesheets %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock stylesheets %}

{% block content %}
    <div class="menu-container">
        <div class="animated fadeIn">
            <div class="card row bg-info text-white">
                <div class="col-md-12 bg-info text-white p-4">
                    <div class="row">
                        <div class="col-md-8 col-lg-8 mb-3">
                            <h3>
                                <i class="fa fa-edit"></i> <strong class="my-floor"> FILL ORDER</strong>
                            </h3>
                        </div>                 
                    </div>
                </div>
                <div class="col-md-12 bg-white text-dark p-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h6>Attendant: {{ object.attendant_id.user_id.name }}</h6>
                        </div>
                        <div class="col-md-6">
                            <h6>Base: {{ object.base }}</h6>
                        </div>
                        <div class="col-md-6">
                            <h6>Date: {{ object.date }}</h6>
                        </div>
                        <div class="col-md-12">
                            <form action="" method="post">
                                {% csrf_token %}
                                {% if messages %}
                                    {% for message in messages %}
                                        <p class="text-danger text-center font-weight-bold p-4">{{ message }}</p>
                                    {% endfor %}
                                {% endif %}
                                <table class="table table-strip table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Product</th>
                                            <th>Quantity</th>
                                            <th>Price</th>
                                            <th>Total Price</th>
                                            <th>Fill Quantity</th>
                                            <th>Add Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product in object.orderline.all %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ product.product_id }}</td>
                                            <td>{{ product.quantity }}</td>
                                            <td>{{ product.product_id.price }}</td>
                                            <td>{{ product.total_product_price }}</td>
                                            <td>{{ product.fill_quantity }}</td>
                                            <td>
                                                <input type="number" class="form-control" name="{{ product.id }}_quantity" id="{{ product.id }}_quantity" placeholder="Enter quantity">
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <button class="btn btn-primary" type="submit">FILL THIS ORDER</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/inventory/order_details.html
{% extends "dashboard/base/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block stylesheets %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock stylesheets %}

{% block content %}
    <div class="menu-container">
        <div class="animated fadeIn">
            <div class="card row bg-info text-white">
                <div class="col-md-12 bg-info text-white p-4">
                    <div class="row">
                        <div class="col-md-8 col-lg-8 mb-3">
                            <h3>
                                <i class="fa fa-edit"></i> <strong class="my-floor"> ORDER DETAILS</strong>
                            </h3>
                        </div>
                        <div class="col-md-4 col-lg-4 text-center">
                            {% if request.user.user_type == 'provider' and object.attendant_id.plane_id.status == 'land'%}
                                <a href="{% url 'inventory:fill_order' object.pk %}" class="btn btn-primary text-right">FILL THIS ORDER</a>
                            {% endif %}
                            <a href="{% url 'inventory:download_order_pdf' object.pk %}" class="btn btn-secondary text-right">DOWNLOAD</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 bg-white text-dark p-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h6>Attendant: {{ object.attendant_id.user_id.name }}</h6>
                        </div>
                        <div class="col-md-6">
                            <h6>Base: {{ object.base }}</h6>
                        </div>
                        <div class="col-md-6">
                            <h6>Date: {{ object.date }}</h6>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-strip table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th>SL</th>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Filled Quantity</th>
                                        <th>Price</th>
                                        <th>Total Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in object.orderline.all %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ product.product_id }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.fill_quantity }}</td>
                                        <td>{{ product.product_id.price }}</td>
                                        <td>{{ product.total_product_price }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/inventory/order_list.html
{% extends "dashboard/base/base.html" %}
{% load static %}

{% block content %}
<div class="card">
    <div class="table-responsive">
        <table class="table align-items-center mb-0">
            <thead>
                <tr>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">SL</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Attendant</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Base</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Date</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Status</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <span class="text-dark text-xs font-weight-bold">{{ object.attendant_id }}</span>
                        </td>
                        <td>
                            <span class="text-dark text-xs font-weight-bold">{{ object.base }}</span>
                        </td>
                        <td>
                            <span class="text-dark text-xs font-weight-bold">{{ object.date }}</span>
                        </td>
                        <td>
                            <span class="text-dark text-xs font-weight-bold">{{ object.status }}</span>
                        </td>
                        <td>
                            <a href="{% url 'inventory:order_details' object.pk %}" class="btn btn-primary">View</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td  colspan="6" class="text-center text-danger">No Order Found!</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="p-4">
        <form action="{% url 'inventory:download_order_list_pdf' %}" method="get">
            <div class="row">
                <div class="col-md-2">
                    <button class="btn btn-info" type="submit">Download</button>
                </div>
                <div class="col-md-2">
                    <input type="date" name="download_date" id="download_date" class="form-control" required>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/inventory/plane_list.html
{% extends "dashboard/base/base.html" %}
{% load static %}

{% block content %}
<div class="card">
    <div class="table-responsive">
        <table class="table align-items-center mb-0">
            <thead>
                <tr>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Name</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Status</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Actual Stock</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Action</th>
                    <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Change Status</th>
                </tr>
            </thead>
            <tbody>
                {% if request.user.user_type == 'attendant' and planes %}
                    <tr>
                        <td>
                            <span class="text-dark text-xs font-weight-bold">{{ planes.name }}</span>
                        </td>
                        <td>
                            {% if planes.status == 'air' %}
                                <span class="text-dark text-xs font-weight-bold badge text-success">Air</span>
                            {% else %}
                                <span class="text-dark text-xs font-weight-bold badge text-danger">Land</span>
                            {% endif %}
                        </td>
                        <td>{{ planes.get_actual_stock }}</td>
                        <td>
                            {% if planes.status == 'air' %}
                                <a href="{% url 'inventory:order' planes.pk %}" class="btn btn-primary">Order</a>
                            {% else %}
                                <a href="" class="btn btn-secondary disabled">Order</a>
                            {% endif %}
                        </td>
                        <td>
                            {% if planes.status == 'air' %}
                                <a href="{% url 'inventory:change_plane_status' planes.pk %}" class="btn btn-info">Change to Land</a>
                            {% else %}
                            <a href="{% url 'inventory:change_plane_status' planes.pk %}" class="btn btn-success">Change to Air</a>
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td  colspan="3" class="text-center text-danger">No Plane Found!</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
<h6 class="mt-4">Products</h6>
<table class="table align-items-center mt-4">
    <thead>
        <tr>
            <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Name</th>
            <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Quantity</th>
            <th class="text-uppercase text-dark text-xxs font-weight-bold ps-2">Max Stock</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in planes.planestock.all %}
            <tr>
                <td>
                    <span class="text-dark text-xs font-weight-bold">{{ stock.product_id.name }}</span>
                </td>
                <td>{{ stock.quantity }}</td>
                <td>{{ stock.maximum_quantity }}</td>
            </tr>
        {% empty %}
            <tr>
                <td  colspan="3" class="text-center text-danger">No Stock Found!</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}