inventory/urls.py
from django.urls import path

from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('plane/list/', views.PlaneListView.as_view(), name='plane_list'),
    path('order/list/', views.OrderListView.as_view(), name='order_list'),
    # path('order/', views.OrderCreateView.as_view(), name='order'),
    path('order/<int:pk>/', views.StockOrderView.as_view(), name='order'),
    path(
        'order/<int:pk>/details/', views.OrderDetailView.as_view(),
        name='order_details'
    ),
    path(
        'order/<int:pk>/fill/', views.FillOrderView.as_view(),
        name='fill_order'
    ),
    path(
        'change/<int:pk>/status/', views.ChangePlaneStatusView.as_view(),
        name='change_plane_status'
    ),
    path(
        'order/<int:pk>/download/', views.OrderPDFView.as_view(),
        name='download_order_pdf'
    ),
    path(
        'order/list/download/', views.OrderListPDFView.as_view(),
        name='download_order_list_pdf'
    ),
]

inventory_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('customauth.urls')),
    path('', include('inventory.urls')),
]

inventory/views/dashboard.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

from inventory.models import Planes, Orders, Attendants, Providers


class DashboardView(LoginRequiredMixin, View):
    """ Dashboard view """
    template_name = 'dashboard/dashboard.html'
    login_url = 'customauth:login'

    def get(self, request):
        context = {
            'plane': Planes.objects.all().count(),
            'planes': Planes.objects.all(),
            'order': Orders.objects.all().count(),
            'attendant': Attendants.objects.all().count(),
            'provider': Providers.objects.all().count(),
        }
        return render(request, self.template_name, context)

templates/dashboard/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'dashboard/favicon/apple-icon-57x57.png' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'dashboard/favicon/apple-icon-60x60.png' %}">
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'dashboard/favicon/apple-icon-72x72.png' %}">
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'dashboard/favicon/apple-icon-76x76.png' %}">
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'dashboard/favicon/apple-icon-114x114.png' %}">
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'dashboard/favicon/apple-icon-120x120.png' %}">
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'dashboard/favicon/apple-icon-144x144.png' %}">
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'dashboard/favicon/apple-icon-152x152.png' %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dashboard/favicon/apple-icon-180x180.png' %}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'dashboard/favicon/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'dashboard/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'dashboard/favicon/favicon-96x96.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashboard/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <title>
            Dashboard
        </title>
        <!--     Fonts and icons     -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
        <!-- Nucleo Icons -->
        <link href="{% static 'dashboard/css/nucleo-icons.css' %}" rel="stylesheet" />
        <link href="{% static 'dashboard/css/nucleo-svg.css' %}" rel="stylesheet" />
        <!-- Font Awesome Icons -->
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
        <link href="{% static 'dashboard/css/nucleo-svg.css' %}" rel="stylesheet" />
        <!-- CSS Files -->
        <link id="pagestyle" href="{% static 'dashboard/css/style.css' %}" rel="stylesheet" />
        {% block stylesheets %}
        {% endblock stylesheets %}
    </head>

    <body class="g-sidenav-show bg-gray-100">
        {% include 'dashboard/base/sidebar.html' %}
        <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg">
            <!-- Navbar -->
            {% include 'dashboard/base/navbar.html' %}
            <!-- End Navbar -->
            <div class="container-fluid py-4">
                {% block content %}
                {% endblock content %}
                <footer class="footer pt-3" style="margin-top: 250px;">
                    <div class="container-fluid">
                        <div class="row align-items-center justify-content-lg-between">
                            <div class="col-lg-6 mb-lg-0 mb-4">
                                <div class="copyright text-center text-sm text-muted text-lg-start">
                                    Copyright &copy;
                                    <script>
                                        document.write(new Date().getFullYear());
                                    </script>
                                    JumboTravel
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                                    <li class="nav-item">
                                        <a href="#" class="nav-link text-muted" target="_blank">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#" class="nav-link pe-0 text-muted" target="_blank">Document</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </main>
        <div class="fixed-plugin">
            <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
                <i class="fa fa-cog py-2"> </i>
            </a>
            <div class="card shadow-lg">
                <div class="card-header pb-0 pt-3">
                    <div class="float-start">
                        <h5 class="mt-3 mb-0">Dashboard Configurator</h5>
                        <p>See our dashboard options.</p>
                    </div>
                    <div class="float-end mt-4">
                        <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                            <i class="fa fa-close"></i>
                        </button>
                    </div>
                    <!-- End Toggle Button -->
                </div>
                <hr class="horizontal dark my-1" />
                <div class="card-body pt-sm-3 pt-0">
                    <!-- Sidebar Backgrounds -->
                    <div>
                        <h6 class="mb-0">Sidebar Colors</h6>
                    </div>
                    <a href="javascript:void(0)" class="switch-trigger background-color">
                        <div class="badge-colors my-2 text-start">
                            <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                        </div>
                    </a>
                    <!-- Sidenav Type -->
                    <div class="mt-3">
                        <h6 class="mb-0">Sidenav Type</h6>
                        <p class="text-sm">Choose between 2 different sidenav types.</p>
                    </div>
                    <div class="d-flex">
                        <button class="btn bg-gradient-primary w-100 px-3 mb-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
                        <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
                    </div>
                    <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
                    <!-- Navbar Fixed -->
                    <div class="mt-3">
                        <h6 class="mb-0">Navbar Fixed</h6>
                    </div>
                    <div class="form-check form-switch ps-0">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)" />
                    </div>
                    <hr class="horizontal dark my-sm-4" />
                    <a class="btn bg-gradient-dark w-100" href="#">Free Download</a>
                    <a class="btn btn-outline-dark w-100" href="#">View documentation</a>
                </div>
            </div>
        </div>
        <!--   Core JS Files   -->
        <script src="{% static 'dashboard/js/core/popper.min.js' %}"></script>
        <script src="{% static 'dashboard/js/core/bootstrap.min.js' %}"></script>
        <script src="{% static 'dashboard/js/plugins/perfect-scrollbar.min.js' %}"></script>
        <script src="{% static 'dashboard/js/plugins/smooth-scrollbar.min.js' %}"></script>
        <script>
            var win = navigator.platform.indexOf("Win") > -1;
            if (win && document.querySelector("#sidenav-scrollbar")) {
                var options = {
                    damping: "0.5",
                };
                Scrollbar.init(document.querySelector("#sidenav-scrollbar"), options);
            }
        </script>
        <!-- Github buttons -->
        <script async defer src="https://buttons.github.io/buttons.js"></script>
        <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="{% static 'dashboard/js/boilerplate.min.js' %}"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

templates/dashboard/base/navbar.html
{% load static %}

<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
                <li class="breadcrumb-item text-sm text-dark active" aria-current="page">
                    <a href="{% url 'inventory:dashboard' %}">Dashboard</a>
                </li>
            </ol>
            <h6 class="font-weight-bolder mb-0">Dashboard</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                <div class="input-group">
                    <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" placeholder="Type here..." />
                </div>
            </div>
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-outline-primary btn-sm mb-0 me-3" target="_blank" href="#">View Site</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body font-weight-bold px-0">
                        <i class="fa fa-user me-sm-1"></i>
                        <span class="d-sm-inline d-none">{{ request.user.name }}</span>
                    </a>
                </li>
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </a>
                </li>
                <li class="nav-item px-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0">
                        <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
                    </a>
                </li>
                <li class="nav-item dropdown pe-2 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-bell cursor-pointer"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                        {% for notification in request.user.notifications.all %}
                            <li>
                                <a class="dropdown-item border-radius-md" href="{% if notification.order_id %}{% url 'inventory:order_details' notification.order_id %}{% endif %}">
                                    <div class="d-flex py-1">
                                        <div class="avatar avatar-sm bg-gradient-secondary me-3 my-auto">
                                            <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                                <title>credit-card</title>
                                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                    <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                                                        <g transform="translate(1716.000000, 291.000000)">
                                                            <g transform="translate(453.000000, 454.000000)">
                                                                <path
                                                                    class="color-background"
                                                                    d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z"
                                                                    opacity="0.593633743"
                                                                ></path>
                                                                <path
                                                                    class="color-background"
                                                                    d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"
                                                                ></path>
                                                            </g>
                                                        </g>
                                                    </g>
                                                </g>
                                            </svg>
                                        </div>
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="text-sm font-weight-normal mb-1">
                                                {{ notification.description }}
                                            </h6>
                                            <p class="text-xs text-secondary mb-0">
                                                <i class="fa fa-clock me-1"></i>
                                                {{ notification.created_at }}
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        {% empty %}
                            <li>
                                <div class="d-flex flex-column justify-content-center">
                                    <p class="text-xs text-danger mb-0">No notification found!</p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>